front_left_traction_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_front_left_traction_wheel_joint

front_left_steer_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_front_left_steer_wheel_joint

front_right_traction_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_front_right_traction_wheel_joint

front_right_steer_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_front_right_steer_wheel_joint

back_left_traction_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_back_left_traction_wheel_joint

back_left_steer_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_back_left_steer_wheel_joint

back_right_traction_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_back_right_traction_wheel_joint

back_right_steer_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_back_right_steer_wheel_joint


base_controller:
  type: omni_drive_controller/OmniDriveController
  traction:
    front_right:
      joint_name: rbsherpa_hl_a_front_right_traction_wheel_joint
      max_speed: 20.0 # rad/s
    front_left:
      joint_name: rbsherpa_hl_a_front_left_traction_wheel_joint
      max_speed: 20.0 # rad/s
    back_right:
      joint_name: rbsherpa_hl_a_back_right_traction_wheel_joint
      max_speed: 20.0 # rad/s
    back_left:
      joint_name: rbsherpa_hl_a_back_left_traction_wheel_joint
      max_speed: 20.0 # rad/s
  steer:
    front_right:
      joint_name: rbsherpa_hl_a_front_right_steer_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    front_left:
      joint_name: rbsherpa_hl_a_front_left_steer_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    back_right:
      joint_name: rbsherpa_hl_a_back_right_steer_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    back_left:
      joint_name: rbsherpa_hl_a_back_left_steer_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
  linear_speed_limit: 2.8
  linear_acceleration_limit: 2.0
  angular_speed_limit: 2.0
  angular_acceleration_limit: 2.0
  odom_frame: rbsherpa_hl_a_odom
  robot_base_frame: rbsherpa_hl_a_base_footprint
  odom_broadcast_tf: true
  odom_topic: /rbsherpa_hl_a/odom
  wheel_base: 1.42 #from cad
  track_width: 0.72 #from cad
  wheel_diameter: 0.3684 #  from cad
  cmd_watchdog_duration: 0.2
  odom_publish_frequency: 100


joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

# Settings for ros_control hardware interface
hardware_interface:
  joints:
     - rbsherpa_hl_a_front_right_steer_wheel_joint
     - rbsherpa_hl_a_front_left_steer_wheel_joint
     - rbsherpa_hl_a_back_right_steer_wheel_joint
     - rbsherpa_hl_a_back_left_steer_wheel_joint
     - rbsherpa_hl_a_front_right_traction_wheel_joint
     - rbsherpa_hl_a_front_left_traction_wheel_joint
     - rbsherpa_hl_a_back_right_traction_wheel_joint
     - rbsherpa_hl_a_back_left_traction_wheel_joint
