front_left_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_front_left_wheel_traction_joint

front_left_wheel_steer_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_front_left_wheel_steer_joint

front_right_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_front_right_wheel_traction_joint

front_right_wheel_steer_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_front_right_wheel_steer_joint

back_left_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_back_left_wheel_traction_joint

back_right_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_a_back_right_wheel_traction_joint

structure_position_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_torso_elevator_joint

pan_position_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_torso_pantilt_pan_joint

tilt_position_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_torso_pantilt_tilt_joint 

gimbal_roll_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_gimbal_roll_joint

gimbal_pitch_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_gimbal_pitch_joint

gimbal_yaw_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_a_gimbal_yaw_joint


base_controller:
  type: rbsherpa_hl_omni_controller/RbSherpaHlOmniController
  traction:
    front_right:
      joint_name: rbsherpa_hl_a_front_right_wheel_traction_joint
      max_speed: 20.0 # rad/s
    front_left:
      joint_name: rbsherpa_hl_a_front_left_wheel_traction_joint
      max_speed: 20.0 # rad/s
    back_right:
      joint_name: rbsherpa_hl_a_back_right_wheel_traction_joint
      max_speed: 20.0 # rad/s
    back_left:
      joint_name: rbsherpa_hl_a_back_left_wheel_traction_joint
      max_speed: 20.0 # rad/s
  steer:
    front_right:
      joint_name: rbsherpa_hl_a_front_right_wheel_steer_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    front_left:
      joint_name: rbsherpa_hl_a_front_left_wheel_steer_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    back_right:
      joint_name: rbsherpa_hl_a_back_right_wheel_steer_joint
      min_angle: -3.1 # rads
      max_angle: 3.1
    back_left:
      joint_name: rbsherpa_hl_a_back_left_wheel_steer_joint
      min_angle: -3.1 # rads
      max_angle: 3.1
  linear_speed_limit: 2.8
  linear_acceleration_limit: 2.0
  angular_speed_limit: 2.0
  angular_acceleration_limit: 2.0
  odom_frame: rbsherpa_hl_a_odom
  robot_base_frame: rbsherpa_hl_a_base_footprint
  odom_broadcast_tf: true
  odom_topic: odom
  command_topic: cmd_vel
  wheel_base: 1.244 #from cad
  track_width: 0.734 #from cad
  wheel_diameter: 0.31 #  from cad
  cmd_watchdog_duration: 0.2
  odom_publish_frequency: 100


joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

joint_read_command_controller:
    type: joint_read_command_controller/JointReadCommandController 
    publish_rate: 100.0

