gazebo_ros_control:
  pid_gains:
    rbsherpa_hl_a_front_right_wheel_steer_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    rbsherpa_hl_a_front_left_wheel_steer_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
